name: Node.js CI/CD

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: pwd
      - run: npm install --force
      - run: npm run build
      - run: pm2 start build/server.js --name="algo-trade"
